CREATE TABLE work(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description TEXT DEFAULT NULL,
	parent BIGINT UNSIGNED,
	CONSTRAINT parent_work_fk FOREIGN KEY (parent) REFERENCES work(id) ON DELETE SET NULL ON UPDATE CASCADE
);

