CREATE TABLE work(
	id int PRIMARY_KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	description TEXT DEFAULT NULL,
	work INT CONSTRAINT work_work_fk FOREIGN KEY REFERENCES work(id)
);

CREATE TABLE sound(
	id INT PRIMARY_KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	filename VARCHAR(255) NOT NULL,
	content TEXT DEFAULT NULL,
	signature VARCHAR(255) DEFAULT NULL,
	work INT CONSTRAINT sound_work_fk FOREIGN KEY REFERENCES work(id)
);
