CREATE TABLE sound(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	filename VARCHAR(255) NOT NULL,
	content TEXT DEFAULT NULL,
	signature VARCHAR(255) DEFAULT NULL,
	work BIGINT UNSIGNED,
	CONSTRAINT sound_work_fk FOREIGN KEY (work) REFERENCES work(id) ON DELETE SET NULL ON UPDATE CASCADE
);

